sudo: false
dist: trusty

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: required
    - python: "3.8-dev"
      dist: xenial
      sudo: required
  allow_failures:
    - python: "3.8-dev"
cache: pip
script:
  - make travis
