---
sudo: false
dist: xenial
language: python
matrix:
  include:
    - python: "2.7"
      env: TOXENV=py
    # py2 linting build (flake8 on py2 can flag different stuff)
    - python: "2.7"
      env: TOXENV=py2-lint
    # test on 3.5, 3.6, 3.7
    - python: "3.5"
      env: TOXENV=py
    - python: "3.6"
      env: TOXENV=py
    # separate py3.6 linting build, which runs 'black --check' (no py2 support)
    - python: "3.6"
      env: TOXENV=py36-lint
    # hack py37, py38 to use a different Travis worker type
    # sudo:required gets us the VM builds where these pythons work
    - python: "3.7"
      env: TOXENV=py
      sudo: required
    # windows testing
    - os: windows
      language: sh
      python: "2.7"
      env: TOXENV=py,py2-lint
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip setuptools
    - os: windows
      language: sh
      python: "3.7"
      env: TOXENV=py,py37-lint
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python -m pip install --upgrade pip setuptools
cache: pip
install:
  - pip install -U pip setuptools
  - pip install tox
script:
  - tox
