---
sudo: false
dist: xenial
language: python
matrix:
  include:
    # windows testing
    - os: windows
      language: sh
      python: "2.7"
      env: TOXENV=py,lint
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip setuptools
    - os: windows
      language: sh
      python: "3.7"
      env: TOXENV=py,py37-lint
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python -m pip install --upgrade pip setuptools
cache: pip
install:
  - pip install -U pip setuptools
  - pip install -e '.[development]'
script:
  - tox
